%% compiling all source data in a singloe xls file

addpath(genpath('..\..'))

clear
close all

filename='Source Data.xlsx';
delete(filename)

sheets={};

%% fig 3a
clearvars -except filename sheets

load('fig3a.mat')

% 3a
sheet='Figure 3a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% experimental data
writecell({'Experimental data'; 'Growth rate'; 'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(data.ydata.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

% model predictions - caption
writecell({'Model predictions'; 'Growth rate'; 'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(ymodel.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

%% fig 3bcd
clearvars -except filename sheets

load('fig3bcd.mat')

% 3b
sheet='Figure 3b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% 3b - experimental data
writecell({'Experimental data'; 'Growth rate'; 'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(data_rib.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

% 3b - model predictions
writecell({'Model predictions'; 'Growth rate'; 'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([l_map; phir_map],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 3c
sheet='Figure 3c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% 3c - experimental data
writecell({'Experimental data'; 'Growth rate'; 'Translation elongation rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(data_el.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

% 3c - model predictions
writecell({'Model predictions'; 'Growth rate'; 'Translation elongation rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([l_map; el_map],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 3d
sheet='Figure 3d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% 3d - experimental data - caption
writecell({'Experimental data'; 'Growth rate'; 'Norm. ppGpp conc.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(data_el.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

% 3d - model predictions - caption
writecell({'Model predictions'; 'Growth rate'; 'Norm. ppGpp conc.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([l_map; el_map],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

%% fig3e
clearvars -except filename sheets

load('fig3e.mat')

% 3e
sheet='Figure 3e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% experimental data - caption
writecell({'Nutrient quality'; 'Growth rate ratio to optimal'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([nutrients; l_map(1,:)./l_map(2,:)],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+4;

%% fig4b
clearvars -except filename sheets

load('fig4b.mat')

% 4b
sheet='Figure 4b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% three system trajectories
writecell({'System trajectories'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;

writecell({'f1=4nM';'p_s1';'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([x_het(i_start_obs:end,3), x_het(i_start_obs:end,4)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'f1=20nM';'p_s1';'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([x_het(i_start_obs:end,3), x_het(i_start_obs:end,4)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'f1=800nM';'p_s1';'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([x_het(i_start_obs:end,3), x_het(i_start_obs:end,4)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+4;

% system equilibria
writecell({'System equilibria';'p_s1';'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(eqbs,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

%% fig4de
clearvars -except filename sheets

load('fig4de.mat')


% 4d
sheet='Figure 4d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'p_t7=0';'t';'p_t7'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_fromlow.'; x_fromlow(:,11).'],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'p_t7=500nM';'t';'p_t7'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_fromhigh.'; x_fromhigh(:,11).'],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 4e
sheet='Figure 4e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'p_t7=0';'t';'lambda'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_fromlow, l_fromlow].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'p_t7=500nM';'t';'lambda'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_fromhigh, l_fromhigh].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

%% fig5 abd

clearvars -except filename sheets

load('fig5abd.mat')

% 5a
sheet='Figure 5a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Numerical simulation results';'Translational burden';'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,plasmid_concs*a_xtra]./kxNB;[phi_het0,phi_hets]],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'Analytical predictions';'Translational burden';'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,plasmid_concs*a_xtra]./kxNB;[phi_het0_approx,phi_hets_approx]],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 5b
sheet='Figure 5b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Numerical simulation results';'Translational burden';'Growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,plasmid_concs*a_xtra]./kxNB;[l0,ls]],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'Analytical predictions';'Translational burden';'Growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,plasmid_concs*a_xtra]./kxNB;[l0_approx,ls_approx]],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 5d
sheet='Figure 5d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Numerical simulation results';'Translational burden';'Total protein production rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,plasmid_concs*a_xtra]./kxNB;[mu_het0,mu_hets]],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'Analytical predictions';'Translational burden';'Total protein production rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,plasmid_concs*a_xtra]./kxNB;[mu_het0_approx,mu_hets_approx]],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'Optimal translational burden';'Numerically determined';'Analytically estimated'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([plasmid_concs(index_of_max_mu)*a_xtra./kxNB; xi_max_approx],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

%% fig5c

clearvars -except filename sheets

load('fig5c.mat')

% 5c
sheet='Figure 5c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Experimental data';'Het. prot. mass frac.';'Relative growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(data_het.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'Numerical simulation results';'Het. prot. mass frac.';'Relative growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,phi_hets]; [l0,ls]/l0],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

writecell({'Analytical predictions';'Het. prot. mass frac.';'Relative growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([[0,phi_hets_approx];[l0_approx,ls_approx]/l0_approx],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

%% fig7bcdef

clearvars -except filename sheets

load('fig7bcdef.mat')

row_cntr=1;

% 7b
sheet='Figure 7b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance';'m_amp';'m_dist'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+4), rel_dist(:,9+5)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 7c
sheet='Figure 7c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance';'m_sens';'m_anti';'m_act'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+1), rel_dist(:,9+2), rel_dist(:,9+3)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% 7d
sheet='Figure 7d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative p_sens (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, rel_dist_openloop(:,9+sim.num_het+1)/predist_psens_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative p_sens (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+sim.num_het+1)/predist_psens].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+2;

% 7e
sheet='Figure 7e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative growth rate (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, ls_openloop/predist_l_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative growth rate (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, ls/predist_l].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Analytically estimated relative growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([lambda_estimated/predist_l],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

row_cntr=row_cntr+2;

% 7f
sheet='Figure 7f';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative D (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, Ds_openloop/predist_D_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative D (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, Ds/predist_D].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Analytically estimated relative D value'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([D_estimated/predist_D],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

row_cntr=row_cntr+3;

%% fig7g

clearvars -except filename sheets

load('fig7g.mat')

% 7g
sheet='Figure 7g';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Disturbing gene conc'; 'Relative p_sens (open loop)'; 'Relative p_sens (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([plasmid_concs; p_senss_openloop./p_senss_openloop(1); p_senss./p_senss(1)],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+2;

%% fig7h

clearvars -except filename sheets

load('fig7h.mat')

% 7h
sheet='Figure 7h';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Heatmap variable: relative p_sens.';['Heatmap axes: c_dist in column B, chi in row ',num2str(row_cntr+2)]},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+2;

% axes
writematrix(cdists.',...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr+1)])
writematrix(chis,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])

% heatmap
writematrix(rel_psens.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])

%% fig8bc

clearvars -except filename sheets

load('fig8bc.mat')

% 8b
sheet='Figure 8b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Heatmap variable: relative p_sens.';['Heatmap axes: c_dist in column B, Delta(sigma) in row ',num2str(row_cntr+2)]},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+2;

% axes
writematrix(cdists.',...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr+1)])
writematrix(delta_sigmas,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])

% heatmap
writematrix((ss_values_openloop./ref_value_openloop).',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+size(ss_values_openloop,1)+1;

row_cntr=row_cntr+2;

% 8c
sheet='Figure 8c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;
writecell({'Heatmap variable: relative p_sens.';['Heatmap axes: c_dist in column B, Delta(sigma) in row ',num2str(row_cntr+2)]},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+2;

% axes
writematrix(cdists.',...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr+1)])
writematrix(delta_sigmas,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])

% heatmap
writematrix((ss_values./ref_value).',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+size(ss_values_openloop,1)+1;

row_cntr=row_cntr+2;

%% fig 8d

clearvars -except filename sheets

load('fig8d.mat')

% 8d
sheet='Figure 8d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Disturbing gene conc'; 'Relative p_sens (open loop)'; 'Relative p_sens (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([plasmid_concs; p_senss_openloop./p_senss_openloop(1); p_senss./p_senss(1)],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

%% fig 8e

clearvars -except filename sheets

load('fig8e.mat')

% 8e
sheet='Figure 8e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Disturbing gene conc'; 'Relative p_sens (open loop)'; 'Relative p_sens (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([plasmid_concs; p_senss_openloop./p_senss_openloop(1); p_senss./p_senss(1)],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+2;

%% fig9

load('fig9.mat')

% 9b
sheet='Figure 9b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Inducer conc.'; 'c_dist=0 nM, sigma=0.25'; 'c_dist=0 nM, sigma=0.5';'c_dist=500 nM, sigma=0.5'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([inducer_concs; p_xs_nutr_openloop; p_xs_openloop; p_xs_comp_openloop],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+4;

row_cntr=row_cntr+2;

% 9c
sheet='Figure 9c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Inducer conc.'; 'c_dist=0 nM, sigma=0.25'; 'c_dist=0 nM, sigma=0.5';'c_dist=500 nM, sigma=0.5'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([inducer_concs; p_xs_nutr; p_xs; p_xs_comp],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+4;

row_cntr=row_cntr+2;

% 9d
sheet='Figure 9d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Inducer conc.'; 'c_dist=0 nM, sigma=0.25'; 'c_dist=0 nM, sigma=0.5';'c_dist=500 nM, sigma=0.5'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([inducer_concs; p_xs_nutr_openloop./p_xs_openloop; p_xs_openloop./p_xs_openloop; p_xs_comp_openloop./p_xs_openloop],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+4;

row_cntr=row_cntr+2;

% 9e
sheet='Figure 9e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Inducer conc.'; 'c_dist=0 nM, sigma=0.25'; 'c_dist=0 nM, sigma=0.5';'c_dist=500 nM, sigma=0.5'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([inducer_concs; p_xs_nutr./p_xs; p_xs./p_xs; p_xs_comp./p_xs],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+4;

%% figS1

load('figS1.mat')

sheet='Supp. Figure 1';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for upshift_medium = 1:size(upshift_media,2)
    % specify new medium
    writecell({['Upshift from ', base_medium, ' to ', upshift_media{upshift_medium}]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;

    % experimental data
    writecell({'Experimental data';'Time since upshift';'Growth rate'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([data{upshift_medium}.ts, data{upshift_medium}.ls].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;

    % model predictions
    writecell({'Model predictions';'Time since upshift';'Growth rate'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([model{upshift_medium}.ts, model{upshift_medium}.ls].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;

    row_cntr=row_cntr+1;
end


%% figS2a


load('figS2a.mat')

% S2a
sheet='Supp. Figure 2a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% experimental data
writecell({'Experimental data'; 'Growth rate'; 'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(data.ydata.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

% model predictions - MAP extimate of parameters
writecell({'Maximum a posteriori model predictions'; 'Growth rate'; 'Rib. prot. mass frac.'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(ymodel_fitted.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+3;

for sample_cntr=1:num_samples
    % model  predictions with sampled parameter values
    writecell({['Sample ',num2str(sample_cntr),' model predictions']; 'Growth rate'; 'Rib. prot. mass frac.'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix(ymodels{sample_cntr}.',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;
end

row_cntr=row_cntr+2;

%% figS2b

clearvars -except filename sheets

load('figS2b.mat')

% S2b
sheet='Supp. Figure 2b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Heatmap variable: log(likelihood)';['Heatmap axes: alpha_a in column B, alpha_r in row ',num2str(row_cntr+2)]},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+2;

% axes
writematrix(a_rs.',...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr+1)])
writematrix(a_as,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])

% heatmap
writematrix(loglikes.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+size(loglikes,1)+1;

row_cntr=row_cntr+2;

%% figS2cd

clearvars -except filename sheets

load('figS2cd.mat')

% S2c
sheet='Supp. Figure 2c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Log(norm. eigenval)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(eigenvals_log.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

row_cntr=row_cntr+2;

% S2d
sheet='Supp. Figure 2d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'K_epsilon=K_nu';'k_cm';'alpha_r:alpha_a';'nu_max'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix(sens_log([3,4,1,2]).',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+4;

row_cntr=row_cntr+2;

%% figS2e

clearvars -except filename sheets

load('figS2e.mat')

parnames=bckup.parnames;
ranges=bckup.ranges;
parcombs=bckup.parcombs;
loglikes=bckup.loglikes;
points_in_range=size(ranges,2);

% S2e
sheet='Supp. Figure 2e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for i_comb=1:size(parcombs,1)
    % which parameter combination is being considered - x and y histogram ranges
    parcomb=parcombs(i_comb,:);
    x_par=parcomb(1);
    y_par=parcomb(2);

    writecell({'Heatmap variable: log(likelihood)'; ...
        ['Heatmap axes: ', parnames{y_par}, ' in column B, ',parnames{x_par},' in row ',num2str(row_cntr+2)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+2;
    
    % axes
    writematrix(ranges(y_par,:).',...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr+1)])
    writematrix(ranges(x_par,:),...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])

    % heatmap
    writematrix(loglikes(:,:,i_comb).',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+size(loglikes,1)+1;

    row_cntr=row_cntr+1;
end

%% figS3

clearvars -except filename sheets

load('figS3.mat')

% S3a
sheet='Supp. Figure 3a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Heatmap variable: change in epsilon';['Heatmap axes: c_x in column B, sigma in row ',num2str(row_cntr+2)]},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+2;

% axes
writematrix(plasmid_concs.',...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr+1)])
writematrix(sigmas,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])

% heatmap
writematrix(es.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+size(es,1)+1;

row_cntr=row_cntr+2;

% S3b
sheet='Supp. Figure 3b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Heatmap variable: change in F_r';['Heatmap axes: c_x in column B, sigma in row ',num2str(row_cntr+2)]},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+2;

% axes
writematrix(plasmid_concs.',...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr+1)])
writematrix(sigmas,...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])

% heatmap
writematrix(F_rs.',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr+1)])
row_cntr=row_cntr+size(es,1)+1;


%% figS4a

clearvars -except filename sheets

load('figS4a.mat')

% S4a
sheet='Supp. Figure 4a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for i=size(f1_sweep,2):(-1):1 
    writecell({['f1= ',num2str(f1_sweep(i)),' nM']; 'Time'; 'p_s1'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([t_trajs{i}-inducer_add_time+5,pswitch1_trajs{i}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;
end

row_cntr=row_cntr+2;

%% figS4bcd

clearvars -except filename sheets

load('figS4bcd.mat')

% S4b
sheet='Supp. Figure 4b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time'; 'p_s1'; 'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_trajs{1}-67, pswitch1_trajs{1}, pswitch2_trajs{1},].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% S4c
sheet='Supp. Figure 4c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time'; 'p_s1'; 'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_trajs{2}-67, pswitch1_trajs{2}, pswitch2_trajs{2},].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% S4d
sheet='Supp. Figure 4d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time'; 'p_s1'; 'p_s2'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([t_trajs{3}-67, pswitch1_trajs{3}, pswitch2_trajs{3},].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

%% figS4e

clearvars -except filename sheets

load('figS4e.mat')

% S4e
sheet='Supp. Figure 4e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for fd_index=1:size(fold_decreases,2)
    writecell({['upsilon = ', num2str(fold_decreases(fd_index))]; 'p_s1'; 'p_s2'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix(eqbs{fd_index},...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;
end


%% figS5abc

clearvars -except filename sheets

load('figS5abc.mat')

% S5a
sheet='Supp. Figure 5a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for j=size(mt7_range,2):(-1):1 
    writecell({['p_{t7}(0 h)=',num2str(pt7_range(j)),' nM']; 'Time'; 'p_t7'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([t_trajs{1}{j},pt7_trajs{1}{j}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;
end

row_cntr=row_cntr+2;

% S5b
sheet='Supp. Figure 5b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for j=size(mt7_range,2):(-1):1 
    writecell({['p_{t7}(0 h)=',num2str(pt7_range(j)),' nM']; 'Time'; 'p_t7'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([t_trajs{2}{j},pt7_trajs{2}{j}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;
end

row_cntr=row_cntr+2;

% S5c
sheet='Supp. Figure 5c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for j=size(mt7_range,2):(-1):1 
    writecell({['p_{t7}(0 h)=',num2str(pt7_range(j)),' nM']; 'Time'; 'p_t7'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([t_trajs{3}{j},pt7_trajs{3}{j}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr+1)])
    row_cntr=row_cntr+3;
end

row_cntr=row_cntr+2;

%% figS5defg

clearvars -except filename sheets

load('figS5defg.mat')

time_dim = round(cbc_par.end_time/cbc_par.sampling_time)-1;
time_axis=cbc_par.sampling_time*((1:size(pt7_traj,2))-1);
pt7_refs_of_time=zeros(1,size(pt7_traj,2));
for j = 1:size(pt7_range,2)
    pt7_refs_of_time((j-1)*time_dim+1:j*time_dim)=pt7_range(j);
end

% S5d
sheet='Supp. Figure 5d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'gamma_tox';'p_t7'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
writematrix([cbc_results.tox;cbc_results.pt7],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+2;

% S5 efg
sheet='Supp. Figure 5e,f,g';
sheets{end+1}=sheet;
writecell({'For S5e,f,g (CBC trajectories) see .mat files'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;

time_dim = round(cbc_par.end_time/cbc_par.sampling_time)-1;
time_axis=cbc_par.sampling_time*((1:size(pt7_traj,2))-1);
pt7_refs_of_time=zeros(1,size(pt7_traj,2));
for j = 1:size(pt7_range,2)
    pt7_refs_of_time((j-1)*time_dim+1:j*time_dim)=pt7_range(j);
end
Kp_vals_of_time=zeros(1,size(pt7_traj,2));
for j = 1:size(Kp_vals,2)
    Kp_vals_of_time((j-1)*time_dim+1:j*time_dim)=Kp_vals(j);
end

S5e=containers.Map({'time','p_t7 reference signal','p_t7 CBC trajectory'},{time_axis,pt7_refs_of_time,pt7_traj});
save('Supplementary Figure 5e Source Data','S5e')
S5f=containers.Map({'time','gamma_tox CBC trajectory'},{time_axis,u_traj});
save('Supplementary Figure 5f Source Data','S5f')
S5g=containers.Map({'time','feedback gains Kp'},{time_axis,Kp_vals_of_time});
save('Supplementary Figure 5g Source Data','S5g')


%% figS6

row_cntr=1;

load('figS6.mat')

% S6a
sheet='Supp. Figure 6a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance';'m_amp';'m_dist'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+4), rel_dist(:,9+5)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% S6b
sheet='Supp. Figure 6b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance';'m_sens';'m_anti';'m_act'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+1), rel_dist(:,9+2), rel_dist(:,9+3)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% S6c
sheet='Supp. Figure 6c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative p_sens (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, rel_dist_openloop(:,9+sim.num_het+1)/predist_psens_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative p_sens (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+sim.num_het+1)/predist_psens].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+2;

% S6d
sheet='Supp. Figure 6d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative growth rate (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, ls_openloop/predist_l_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative growth rate (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, ls/predist_l].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Analytically estimated relative growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([lambda_estimated/predist_l],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

row_cntr=row_cntr+2;

% S6e
sheet='Supp. Figure 6e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative D (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, Ds_openloop/predist_D_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative D (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, Ds/predist_D].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Analytically estimated relative D value'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([D_estimated/predist_D],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

%% figS7abc

load('figS7abc.mat')

% S7a
sheet='Supp. Figure 7a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for sample_cntr=1:num_samples
    writecell({['Sample ',num2str(sample_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;

    writecell({'Time since disturbance (open loop)';'Relative p_sens (open loop)'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([rel_ts_openloop{sample_cntr}-dist_time-2.5, rel_psens_trajs_openloop{sample_cntr}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
    
    writecell({'Time since disturbance (closed loop)'; 'Relative p_sens (closed loop)'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([rel_ts{sample_cntr}-dist_time-2.5, rel_psens_trajs{sample_cntr}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row_cntr=row_cntr+2;

% S7b
sheet='Supp. Figure 7b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for sample_cntr=1:num_samples
    writecell({['Sample ',num2str(sample_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;

    writecell({'Time since disturbance (open loop)';'Relative lambda (open loop)'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([rel_ts_openloop{sample_cntr}-dist_time-2.5, rel_l_trajs_openloop{sample_cntr}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
    
    writecell({'Time since disturbance (closed loop)'; 'Relative lamda (closed loop)'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([rel_ts{sample_cntr}-dist_time-2.5, rel_l_trajs{sample_cntr}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row_cntr=row_cntr+2;

% S7c
sheet='Supp. Figure 7c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

for sample_cntr=1:num_samples
    writecell({['Sample ',num2str(sample_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;

    writecell({'Time since disturbance (open loop)';'Relative lambda (open loop)'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([rel_ts_openloop{sample_cntr}-dist_time-2.5, rel_D_trajs_openloop{sample_cntr}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
    
    writecell({'Time since disturbance (closed loop)'; 'Relative lamda (closed loop)'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([rel_ts{sample_cntr}-dist_time-2.5, rel_D_trajs{sample_cntr}].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

%% figS7def

clearvars -except filename sheets

load('figS7def.mat')

% S7d
sheet='Supp. Figure 7d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% average open loop trajectory
avg_psens_traj_openloop=mean(psens_trajs_openloop_concatenated,2);
writecell({'Open loop average trajectory'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;
writecell({'Time since disturbance';'Relative p_sens'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ts_openloop{1}(t_in_frame)-dist_time,avg_psens_traj_openloop(t_in_frame)./psens_refmean_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

% average closed loop trajectory
avg_psens_traj=mean(psens_trajs_concatenated,2);
writecell({'Closed loop average trajectory'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;
writecell({'Time since disturbance';'Relative p_sens'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ts{1}(t_in_frame)-dist_time,avg_psens_traj(t_in_frame)./psens_refmean].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+1;

% open loop sampled trajectories
for traj_cntr=1:num_trajs
    % open loop sample
    writecell({['Open loop sample ',num2str(traj_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;
    
    t_in_frame=(ts_openloop{traj_cntr}>=5)&(ts_openloop{traj_cntr}<=12.5);

    writecell({'Time since disturbance';'Relative p_sens'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([ts_openloop{traj_cntr}(t_in_frame)-dist_time, psens_trajs_openloop{traj_cntr}(t_in_frame)./psens_refmean_openloop].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row=row_cntr+1;

% closed loop sampled trajectories
for traj_cntr=1:num_trajs
    % open loop sample
    writecell({['Closed loop sample ',num2str(traj_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;
    
    t_in_frame=(ts_openloop{traj_cntr}>=5)&(ts_openloop{traj_cntr}<=12.5);

    writecell({'Time since disturbance';'Relative p_sens'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([ts_openloop{traj_cntr}(t_in_frame)-dist_time, psens_trajs_openloop{traj_cntr}(t_in_frame)./psens_refmean_openloop].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row_cntr=row_cntr+2;

% S7e
sheet='Supp. Figure 7e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% average open loop trajectory
avg_l_traj_openloop=mean(l_trajs_openloop_concatenated,2);
writecell({'Open loop average trajectory'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;
writecell({'Time since disturbance';'Relative lambda'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ts_openloop{1}(t_in_frame)-dist_time,avg_l_traj_openloop(t_in_frame)./l_refmean_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

% average closed loop trajectory
avg_l_traj=mean(l_trajs_concatenated,2);
writecell({'Closed loop average trajectory'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;
writecell({'Time since disturbance';'Relative lambda'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ts{1}(t_in_frame)-dist_time,avg_l_traj(t_in_frame)./l_refmean].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+1;

% open loop sampled trajectories
for traj_cntr=1:num_trajs
    % open loop sample
    writecell({['Open loop sample ',num2str(traj_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;
    
    t_in_frame=(ts_openloop{traj_cntr}>=5)&(ts_openloop{traj_cntr}<=12.5);

    writecell({'Time since disturbance';'Relative lambda'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([ts_openloop{traj_cntr}(t_in_frame)-dist_time, l_trajs_openloop{traj_cntr}(t_in_frame)./l_refmean_openloop].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row=row_cntr+1;

% closed loop sampled trajectories
for traj_cntr=1:num_trajs
    % open loop sample
    writecell({['Closed loop sample ',num2str(traj_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;
    
    t_in_frame=(ts_openloop{traj_cntr}>=5)&(ts_openloop{traj_cntr}<=12.5);

    writecell({'Time since disturbance';'Relative lambda'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([ts_openloop{traj_cntr}(t_in_frame)-dist_time, l_trajs_openloop{traj_cntr}(t_in_frame)./l_refmean_openloop].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row_cntr=row_cntr+2;

% S7f
sheet='Supp. Figure 7f';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

% average open loop trajectory
avg_D_traj_openloop=mean(D_trajs_openloop_concatenated,2);
writecell({'Open loop average trajectory'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;
writecell({'Time since disturbance';'Relative lambda'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ts_openloop{1}(t_in_frame)-dist_time,avg_D_traj_openloop(t_in_frame)./D_refmean_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

% average closed loop trajectory
avg_D_traj=mean(D_trajs_concatenated,2);
writecell({'Closed loop average trajectory'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
row_cntr=row_cntr+1;
writecell({'Time since disturbance';'Relative lambda'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ts{1}(t_in_frame)-dist_time,avg_D_traj(t_in_frame)./D_refmean].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

row_cntr=row_cntr+1;

% open loop sampled trajectories
for traj_cntr=1:num_trajs
    % open loop sample
    writecell({['Open loop sample ',num2str(traj_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;
    
    t_in_frame=(ts_openloop{traj_cntr}>=5)&(ts_openloop{traj_cntr}<=12.5);

    writecell({'Time since disturbance';'Relative lambda'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([ts_openloop{traj_cntr}(t_in_frame)-dist_time, D_trajs_openloop{traj_cntr}(t_in_frame)./D_refmean_openloop].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row=row_cntr+1;

% closed loop sampled trajectories
for traj_cntr=1:num_trajs
    % open loop sample
    writecell({['Closed loop sample ',num2str(traj_cntr)]},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    row_cntr=row_cntr+1;
    
    t_in_frame=(ts_openloop{traj_cntr}>=5)&(ts_openloop{traj_cntr}<=12.5);

    writecell({'Time since disturbance';'Relative lambda'},...
        filename,'Sheet',sheet,...
        'Range',['B',num2str(row_cntr)])
    writematrix([ts_openloop{traj_cntr}(t_in_frame)-dist_time, D_trajs_openloop{traj_cntr}(t_in_frame)./D_refmean_openloop].',...
        filename,'Sheet',sheet,...
        'Range',['C',num2str(row_cntr)])
    row_cntr=row_cntr+2;
end

row_cntr=row_cntr+2;

%% figS8

clearvars -except filename sheets

load('figS8.mat')

% S8a
sheet='Supp. Figure 8a';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance';'m_amp';'m_dist'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+4), rel_dist(:,9+5)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% S8b
sheet='Supp. Figure 8b';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance';'m_sens';'m_anti';'m_act'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+1), rel_dist(:,9+2), rel_dist(:,9+3)].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+3;

row_cntr=row_cntr+2;

% S8c
sheet='Supp. Figure 8c';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative p_sens (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, rel_dist_openloop(:,9+sim.num_het+1)/predist_psens_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative p_sens (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, rel_dist(:,9+sim.num_het+1)/predist_psens].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;


writecell({'Mean relative p_sens over last 15h'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([psenss_mean/predist_psens],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

row_cntr=row_cntr+2;

% S8d
sheet='Supp. Figure 8d';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative growth rate (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, ls_openloop/predist_l_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative growth rate (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, ls/predist_l].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Analytically estimated relative growth rate'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([lambda_estimated/predist_l],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

writecell({'Mean relative lambda over last 15h'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([ls_mean/predist_l],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

row_cntr=row_cntr+2;

% S8e
sheet='Supp. Figure 8e';
sheets{end+1}=sheet;
writecell({sheet},...
    filename,'Sheet',sheet,...
    'Range',['A',num2str(1)])
row_cntr=3;

writecell({'Time since disturbance (open loop)';'Relative D (open loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t_openloop-dist_time, Ds_openloop/predist_D_openloop].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Time since disturbance (closed loop)'; 'Relative D (closed loop)'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([rel_t-dist_time, Ds/predist_D].',...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+2;

writecell({'Analytically estimated relative D value'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([D_estimated/predist_D],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;

writecell({'Mean relative D over last 15h'},...
    filename,'Sheet',sheet,...
    'Range',['B',num2str(row_cntr)])
writematrix([Ds_mean/predist_D],...
    filename,'Sheet',sheet,...
    'Range',['C',num2str(row_cntr)])
row_cntr=row_cntr+1;